-- =============================================================
-- 02_secuencias.sql
-- Secuencias para generar los id. Empiezan en 1000 (o mas) para
-- que no choquen con los id que usamos en los datos de prueba.
-- =============================================================

CREATE SEQUENCE SEQ_ESTACION        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_SERVICIO        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PLATAFORMA      START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TRANSFERENCIA   START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RUTA            START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HORARIO         START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VIAJE           START WITH 10000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_DEPOSITO        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_MODELO          START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_COMPOSICION     START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CARGO           START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_EMPLEADO        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_CERTIFICACION   START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TURNO           START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_AUSENCIA        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PASAJERO        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_HIST_TARIFA     START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_TARJETA         START WITH 4000000000001000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_RECARGA         START WITH 100000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_VIAJE_PASAJERO  START WITH 500000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDEN           START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_REPUESTO        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_INCIDENTE       START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ELEMENTO        START WITH 1000 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_BITACORA        START WITH 1 INCREMENT BY 1 NOCACHE;
